# Generated by Django 5.1.1 on 2024-10-29 21:24

import django.utils.timezone
import tiendaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, default='empleados/empledo.png', null=True, upload_to=tiendaApp.models.Empleado.generar_nombre),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='materno',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido Materno'),
        ),
    ]
