# Generated by Django 5.1.1 on 2024-11-02 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_empleado_foto_alter_empleado_creado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de cancha')),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada')], default='Disponible', max_length=20)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'db_table': 'cancha',
            },
        ),
    ]
