# Generated by Django 5.1.1 on 2024-11-02 22:13

import django.utils.timezone
import tiendaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_cancha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, verbose_name='RUN')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(blank=True, max_length=50, verbose_name='Apellido Materno')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], default='o', max_length=1)),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('foto', models.ImageField(blank=True, default='empleados/empledo.png', null=True, upload_to=tiendaApp.models.Cliente.generar_nombre)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['nombre', 'paterno', 'materno'],
            },
        ),
    ]
