# Generated by Django 5.1.1 on 2024-11-04 10:29

import django.db.models.deletion
import django.utils.timezone
import tiendaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por hora')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
            },
        ),
        migrations.AddField(
            model_name='cancha',
            name='foto',
            field=models.ImageField(blank=True, default='cancha/todoCancha.jpg', null=True, upload_to=tiendaApp.models.Cancha.generar_cancha),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('mantenimiento', 'En Mantenimiento'), ('ocupada', 'No disponible')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='tipo',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('tenis', 'Tenis'), ('paddle', 'Paddle')], max_length=50, verbose_name='Tipo de cancha'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de reserva')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaApp.cancha', verbose_name='Cancha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaApp.cliente', verbose_name='Cliente')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaApp.horario', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
                'ordering': ['-fecha', '-horario__hora_inicio'],
                'unique_together': {('cancha', 'horario', 'fecha')},
            },
        ),
    ]
