# Generated by Django 5.1.1 on 2024-11-12 17:25

import django.utils.timezone
import tiendaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0005_horario_cancha_foto_alter_cancha_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, verbose_name='RUN')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(blank=True, max_length=50, verbose_name='Apellido Materno')),
                ('especialidad', models.CharField(max_length=50, verbose_name='deporte especializado')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], default='o', max_length=1)),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('foto', models.ImageField(blank=True, default='empleados/empledo.png', null=True, upload_to=tiendaApp.models.Entrenador.generar_nombre)),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
                'db_table': 'entrenador',
                'ordering': ['nombre', 'paterno', 'materno', 'especialidad'],
            },
        ),
    ]
